name: Upload to S3 using AWS CLI

on: 
  push:
    branches:
      - master

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-west-2'  # Specify your AWS region

      - name: Upload directory to S3
        run: aws s3 cp ./uploads s3://${{ secrets.AWS_BUCKET }}/ --recursive --no-acl